# A first workflow to play around with the editor
name: My First Workflow
on:
  push:
    branches:
      - master
    #   - 'release/**'
    # paths:
    #   - 'doc/**'
  workflow_dispatch:
  # schedule:
  #   # Runs at every 15th minute
  #   - cron:  '*/15 * * * *'
  #   # Runs every hour from 9am to 5pm
  #   - cron:  '0 9-17 * * *'
  #   # Runs every Friday at midnight
  #   - cron:  '0 2 * * FRI'

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: echo "Hello world"
        shell: bash
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
          echo "Current branch is '${{ github.ref }}'."
          echo "My secret is  ${{ secrets.MY_SECRET }}."
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: tree

      # # Reference a version using a tag
      # - uses: actions/checkout@v4.2.2
      # # Reference the current head of a branch
      # - uses: actions/checkout@master
      # # Reference a specific commit
      # - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
  
  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: first_job
    steps:
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET }}  from ${{ github.actor }}."
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "My secret is  '$sec'."

  Load-Test:
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: first_job

  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    needs: [Test, Load-Test]